name = "RoseEngine"
uuid = "1fee7e7e-a2d0-4741-9c73-83d563d1c3d3"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"

[compat]
Printf = "1.11.0"
XML = "0.3.4"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
